from pathlib import Path
import os

INPUT_FOLDER = Path("images")
OUTPUT_FOLDER = Path("grouped_images")
DEBUG_FOLDER = Path("debug")
NN_OUTPUT_FOLDER = Path("grouped_images_nn")
NN_EMBEDDING_CANDIDATES_CSV = Path("embedding_candidates.csv")

CPU_COUNT = os.cpu_count() or 1
MAX_WORKERS = max(1, CPU_COUNT - 1)

MAX_IMAGE_SIZE = 800

SUPPORTED_EXTENSIONS = {
    ".jpg", ".jpeg", ".png", ".bmp", ".webp", ".tif", ".tiff"
}

BACKGROUND_THRESHOLD = 245

PHASH_SIZE = 32
PHASH_HASH_SIZE = 8
DHASH_HASH_SIZE = 8

# -------------------- PASS 1 --------------------
# Нормальный первый проход
PASS1_PHASH_MAX_DISTANCE = 24
PASS1_DHASH_MAX_DISTANCE = 24
PASS1_MAX_MASK_AREA_RATIO = 6.0
PASS1_MAX_BBOX_ASPECT_DIFF = 0.80

PASS1_MIN_KEYPOINTS = 10
PASS1_MIN_GOOD_MATCHES = 7
PASS1_MIN_INLIERS = 10
PASS1_MIN_INLIER_RATIO = 0.75
PASS1_RANSAC_REPROJ_THRESHOLD = 6.0

# -------------------- PASS 2 --------------------
# Более мягкий второй проход только по одиночкам
PASS2_PHASH_MAX_DISTANCE = 28
PASS2_DHASH_MAX_DISTANCE = 28
PASS2_MAX_MASK_AREA_RATIO = 10.0
PASS2_MAX_BBOX_ASPECT_DIFF = 1.20

PASS2_MIN_KEYPOINTS = 8
PASS2_MIN_GOOD_MATCHES = 6
PASS2_MIN_INLIERS = 8
PASS2_MIN_INLIER_RATIO = 0.70
PASS2_RANSAC_REPROJ_THRESHOLD = 7.0

# -------------------- ORB --------------------
ORB_NFEATURES = 5000
ORB_SCALE_FACTOR = 1.2
ORB_NLEVELS = 8
ORB_EDGE_THRESHOLD = 15
ORB_PATCH_SIZE = 31
ORB_FAST_THRESHOLD = 10

LOG_LEVEL = "INFO"
LOG_EVERY_N = 100
SAVE_DEBUG_MATCHES = False

# -------------------- Backward compatibility --------------------
# Старые имена параметров нужны для модулей `main.py`/`orb_verify.py`.
# По умолчанию они ссылаются на пороги PASS1.
PHASH_MAX_DISTANCE = PASS1_PHASH_MAX_DISTANCE
DHASH_MAX_DISTANCE = PASS1_DHASH_MAX_DISTANCE
MAX_MASK_AREA_RATIO = PASS1_MAX_MASK_AREA_RATIO
MAX_BBOX_ASPECT_DIFF = PASS1_MAX_BBOX_ASPECT_DIFF
MIN_KEYPOINTS = PASS1_MIN_KEYPOINTS
MIN_GOOD_MATCHES = PASS1_MIN_GOOD_MATCHES
MIN_INLIERS = PASS1_MIN_INLIERS
RANSAC_REPROJ_THRESHOLD = PASS1_RANSAC_REPROJ_THRESHOLD
LOG_EVERY_N_PAIRS = LOG_EVERY_N
